/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Person.Patient;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rimple
 */
public class ViewPatientsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientsJPanel
     */
    private JPanel userProcessContainer;
    private Patient p;

    public ViewPatientsJPanel(JPanel userProcessContainer, Patient p) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.p = p;
        populateFields();
        saveJButton.setVisible(false);

    }

    private void populateFields() {
        firstNameJTextField.setText(p.getFirstName());
        lastNameJTextField.setText(p.getLastName());
        dobJTextField.setText(p.getDateOfBirth());
        genderJTextField.setText(p.getGender());
        maritalStatusJTextField.setText(p.getMaritalStatus());
        ssnJTextField.setText(p.getSsn());
        homeAddressJTextArea.setText(p.getHomeAddress());
        cityJTextField.setText(p.getCity());
        countryJTextField.setText(p.getCountry());
        zipCodeJTextField.setText(String.valueOf(p.getZipCode()));
        homePhoneJTextField.setText(String.valueOf(p.getHomePhone()));
        mobilePhoneJTextField.setText(String.valueOf(p.getMobilePhone()));
        isInsuranceJTextField.setText(p.getIsInsurance());
        insuranceNoJTextField.setText(p.getInsuranceNo());
        insuranceCompanyJTextField.setText(p.getInsuranceCompany());
        preferredDoctorJTextField.setText(p.getPreferredDoctor().getFirstName() + " " + p.getPreferredDoctor().getLastName());
        allergiesJTextField.setText(p.getAllergies());
        commentsJTextArea.setText(p.getComments());
        mrNumberJLabel.setText(String.valueOf(p.getMrNo()));
        registrationDateJTextField.setText(String.valueOf(p.getRegistrationDate()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        homeAddressJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ssnJLabel = new javax.swing.JLabel();
        ssnJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        insuranceNoJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        insuranceCompanyJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        allergiesJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentsJTextArea = new javax.swing.JTextArea();
        dateOfBirthJLabel = new javax.swing.JLabel();
        firstNameJTextField = new javax.swing.JTextField();
        lastNameJTextField = new javax.swing.JTextField();
        genderJLabel = new javax.swing.JLabel();
        firstNameJLabel = new javax.swing.JLabel();
        lastNameJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        countryJLabel = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        countryJTextField = new javax.swing.JTextField();
        zipCodeJLabel = new javax.swing.JLabel();
        cityJTextField = new javax.swing.JTextField();
        zipCodeJTextField = new javax.swing.JTextField();
        homePhoneJLabel = new javax.swing.JLabel();
        homePhoneJTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        homeAddressJTextArea = new javax.swing.JTextArea();
        mobilePhoneJLabel = new javax.swing.JLabel();
        mobilePhoneJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        dobJTextField = new javax.swing.JTextField();
        genderJTextField = new javax.swing.JTextField();
        maritalStatusJTextField = new javax.swing.JTextField();
        isInsuranceJTextField = new javax.swing.JTextField();
        preferredDoctorJTextField = new javax.swing.JTextField();
        mrNoJLabel = new javax.swing.JLabel();
        mrNumberJLabel = new javax.swing.JLabel();
        registrationDateJTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        updateJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();

        headingJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headingJLabel.setText("View Patients");

        homeAddressJLabel.setText("Home Address:");

        jLabel2.setText("Do you have insurance?");

        ssnJLabel.setText("SSN:");

        ssnJTextField.setEnabled(false);

        jLabel3.setText("Insurance Number:");

        insuranceNoJTextField.setEnabled(false);

        jLabel4.setText("Insurance Company:");

        insuranceCompanyJTextField.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Personal Details:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Insurance Details:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Medical Details:");

        jLabel8.setText("Prefferred Doctor:");

        allergiesJTextField.setEnabled(false);

        jLabel9.setText("Any allergies:");

        jLabel10.setText("Comments:");

        commentsJTextArea.setColumns(20);
        commentsJTextArea.setRows(5);
        commentsJTextArea.setEnabled(false);
        jScrollPane1.setViewportView(commentsJTextArea);

        dateOfBirthJLabel.setText("Date Of Birth:");

        firstNameJTextField.setEnabled(false);

        lastNameJTextField.setEnabled(false);

        genderJLabel.setText("Gender:");

        firstNameJLabel.setText("First Name:");

        lastNameJLabel.setText("Last Name:");

        jLabel1.setText("Marital Status:");

        countryJLabel.setText("Country:");

        cityJLabel.setText("City:");

        countryJTextField.setEnabled(false);

        zipCodeJLabel.setText("Postal/Zip code:");

        cityJTextField.setEnabled(false);

        zipCodeJTextField.setEnabled(false);

        homePhoneJLabel.setText("Home Phone:");

        homePhoneJTextField.setEnabled(false);

        homeAddressJTextArea.setColumns(20);
        homeAddressJTextArea.setRows(5);
        homeAddressJTextArea.setEnabled(false);
        jScrollPane2.setViewportView(homeAddressJTextArea);

        mobilePhoneJLabel.setText("Mobile Phone:");

        mobilePhoneJTextField.setEnabled(false);

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        dobJTextField.setEnabled(false);

        genderJTextField.setEnabled(false);

        maritalStatusJTextField.setEnabled(false);

        isInsuranceJTextField.setEnabled(false);

        preferredDoctorJTextField.setEnabled(false);

        mrNoJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mrNoJLabel.setText("MR No.");

        mrNumberJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mrNumberJLabel.setText("jLabel11");

        registrationDateJTextField.setEnabled(false);

        jLabel12.setText("Registration Date:");

        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(258, 258, 258)
                        .addComponent(updateJButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveJButton))
                    .addComponent(homeAddressJLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateOfBirthJLabel)
                            .addComponent(firstNameJLabel)
                            .addComponent(jLabel1)
                            .addComponent(homePhoneJLabel)
                            .addComponent(mobilePhoneJLabel)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homePhoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobilePhoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(headingJLabel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mrNoJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(mrNumberJLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(maritalStatusJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(dobJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(firstNameJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lastNameJLabel)
                                                .addComponent(genderJLabel)
                                                .addComponent(ssnJLabel)
                                                .addComponent(zipCodeJLabel)
                                                .addComponent(cityJLabel))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(insuranceNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(112, 112, 112)
                                            .addComponent(jLabel4)
                                            .addGap(15, 15, 15)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cityJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                                .addComponent(lastNameJTextField)
                                                .addComponent(genderJTextField)
                                                .addComponent(ssnJTextField))
                                            .addGap(76, 76, 76)
                                            .addComponent(countryJLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(countryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(zipCodeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(insuranceCompanyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isInsuranceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(preferredDoctorJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(allergiesJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                            .addComponent(registrationDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(mrNoJLabel)
                            .addComponent(mrNumberJLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(firstNameJLabel)
                                            .addComponent(firstNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastNameJLabel)
                                            .addComponent(lastNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dateOfBirthJLabel)
                                            .addComponent(dobJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(maritalStatusJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(ssnJLabel))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(homeAddressJLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(genderJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ssnJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(84, 84, 84))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityJLabel)
                            .addComponent(countryJLabel)
                            .addComponent(countryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zipCodeJLabel)
                            .addComponent(zipCodeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homePhoneJLabel)
                    .addComponent(homePhoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilePhoneJLabel)
                    .addComponent(mobilePhoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(isInsuranceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(insuranceNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(insuranceCompanyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(preferredDoctorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(allergiesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrationDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(updateJButton)
                    .addComponent(saveJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        saveJButton.setVisible(true);
        firstNameJTextField.setEnabled(true);
        lastNameJTextField.setEnabled(true);
        homeAddressJTextArea.setEnabled(true);
        cityJTextField.setEnabled(true);
        countryJTextField.setEnabled(true);
        zipCodeJTextField.setEnabled(true);
        homePhoneJTextField.setEnabled(true);
        mobilePhoneJTextField.setEnabled(true);
        allergiesJTextField.setEnabled(true);
        commentsJTextArea.setEnabled(true);

    }//GEN-LAST:event_updateJButtonActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed

        try {
            String firstName = firstNameJTextField.getText();
            String lastName = lastNameJTextField.getText();
            String homeAddress = homeAddressJTextArea.getText();
            String city = cityJTextField.getText();
            String country = countryJTextField.getText();
            String zipCode = zipCodeJTextField.getText();
            String homePhone = homePhoneJTextField.getText();
            String mobilePhone = mobilePhoneJTextField.getText();
            String allergies = allergiesJTextField.getText();
            String comments = commentsJTextArea.getText();

            if (("".equals(firstName)) || ("".equals(lastName)) || ("".equals(homeAddress))
                    || ("".equals(city)) || ("".equals(country))
                    || ("".equals(zipCode)) || ("".equals(homePhone)) || ("".equals(mobilePhone))
                    || ("".equals(allergies)) || ("".equals(comments))) {
                JOptionPane.showMessageDialog(null, "Please do not keep any values empty.");
                return;
            }
            Pattern patternString = Pattern.compile("[a-zA-Z ]+");
            Matcher fname = patternString.matcher(firstName);
            Matcher lname = patternString.matcher(lastName);
            Matcher cityName = patternString.matcher(city);
            Matcher countryName = patternString.matcher(country);
            if (fname.matches() && lname.matches() && cityName.matches() && countryName.matches()) {

                p.setFirstName(firstName);
                p.setLastName(lastName);
                p.setCity(cityJTextField.getText());
                p.setCountry(countryJTextField.getText());
            } else {
                JOptionPane.showMessageDialog(null, "only alphabets are allowed for name, city, country.");
                return;
            }
            p.setZipCode(Integer.parseInt(zipCodeJTextField.getText()));

            Pattern pattern = Pattern.compile("\\d{10}");
            Matcher homePho = pattern.matcher(homePhoneJTextField.getText());
            Matcher mobilePho = pattern.matcher(mobilePhoneJTextField.getText());
            if ((homePho.matches()) && (mobilePho.matches())) {
                p.setHomePhone(Long.parseLong(homePhone));
                p.setMobilePhone(Long.parseLong(mobilePhone));
            } else {
                JOptionPane.showMessageDialog(null, "Phone number not valid. Only 10 numbers are allowed");
                return;
            }
            p.setAllergies(allergies);
            p.setComments(comments);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please use numbers for Postal/Zip Code, Home Phone, Mobile Phone");
        }
    }//GEN-LAST:event_saveJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField allergiesJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JTextArea commentsJTextArea;
    private javax.swing.JLabel countryJLabel;
    private javax.swing.JTextField countryJTextField;
    private javax.swing.JLabel dateOfBirthJLabel;
    private javax.swing.JTextField dobJTextField;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameJTextField;
    private javax.swing.JLabel genderJLabel;
    private javax.swing.JTextField genderJTextField;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JLabel homeAddressJLabel;
    private javax.swing.JTextArea homeAddressJTextArea;
    private javax.swing.JLabel homePhoneJLabel;
    private javax.swing.JTextField homePhoneJTextField;
    private javax.swing.JTextField insuranceCompanyJTextField;
    private javax.swing.JTextField insuranceNoJTextField;
    private javax.swing.JTextField isInsuranceJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameJTextField;
    private javax.swing.JTextField maritalStatusJTextField;
    private javax.swing.JLabel mobilePhoneJLabel;
    private javax.swing.JTextField mobilePhoneJTextField;
    private javax.swing.JLabel mrNoJLabel;
    private javax.swing.JLabel mrNumberJLabel;
    private javax.swing.JTextField preferredDoctorJTextField;
    private javax.swing.JTextField registrationDateJTextField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JLabel ssnJLabel;
    private javax.swing.JTextField ssnJTextField;
    private javax.swing.JButton updateJButton;
    private javax.swing.JLabel zipCodeJLabel;
    private javax.swing.JTextField zipCodeJTextField;
    // End of variables declaration//GEN-END:variables
}
