/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmaciesRole;

import Business.Enterprise.Enterprise;
import Business.WorkQueue.EnterpriseAdminWorkRequest;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rimple
 */
public class ManagePharmaciesWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePharamaciesWorkRequestJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;

    public ManagePharmaciesWorkRequestJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populatePatients();
        patientDetailsJPanel.setVisible(false);
    }

    private void populatePatients() {
        DefaultTableModel model = (DefaultTableModel) manageWorkRequestsJTable.getModel();
        model.setRowCount(0);
        for (WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof PharmacyWorkRequest) {
                PharmacyWorkRequest pwr = (PharmacyWorkRequest) wr;
                Object[] row = new Object[5];
                row[0] = pwr;
                row[1] = pwr.getPatient().getFirstName() + " " + pwr.getPatient().getLastName();
                row[2] = pwr.getSender().getFirstName() + " " + pwr.getSender().getLastName();
                row[3] = pwr.getEnterprise();
                row[4] = pwr.getStatus();
                model.addRow(row);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageWorkRequestsJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        viewPateintsJButton = new javax.swing.JButton();
        patientDetailsJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        patientNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mobilePhoneJjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cityJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        drugsJTextArea = new javax.swing.JTextArea();
        processWorkJButton = new javax.swing.JButton();

        headingJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headingJLabel.setText("Manage Work Requests");

        manageWorkRequestsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Patient Name", "Doctor Name", "Enterprise", " Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageWorkRequestsJTable);
        if (manageWorkRequestsJTable.getColumnModel().getColumnCount() > 0) {
            manageWorkRequestsJTable.getColumnModel().getColumn(4).setPreferredWidth(150);
        }

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        viewPateintsJButton.setText("View patient Details");
        viewPateintsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPateintsJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Patient Name:");

        patientNameJTextField.setEditable(false);

        jLabel2.setText("Mobile Phone:");

        addressJTextField.setEditable(false);

        jLabel3.setText("Address:");

        mobilePhoneJjTextField.setEditable(false);

        jLabel4.setText("City:");

        cityJTextField.setEditable(false);

        jLabel5.setText("Drugs:");

        drugsJTextArea.setEditable(false);
        drugsJTextArea.setColumns(20);
        drugsJTextArea.setRows(5);
        jScrollPane2.setViewportView(drugsJTextArea);

        javax.swing.GroupLayout patientDetailsJPanelLayout = new javax.swing.GroupLayout(patientDetailsJPanel);
        patientDetailsJPanel.setLayout(patientDetailsJPanelLayout);
        patientDetailsJPanelLayout.setHorizontalGroup(
            patientDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientDetailsJPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(patientDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(52, 52, 52)
                .addGroup(patientDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(patientDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(patientNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addComponent(addressJTextField)
                        .addComponent(mobilePhoneJjTextField)
                        .addComponent(cityJTextField)))
                .addGap(30, 30, 30))
        );
        patientDetailsJPanelLayout.setVerticalGroup(
            patientDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientDetailsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(patientNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(patientDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mobilePhoneJjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        processWorkJButton.setText("Process Work Request");
        processWorkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processWorkJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(refreshJButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(111, 111, 111)
                        .addComponent(viewPateintsJButton)
                        .addGap(119, 119, 119)
                        .addComponent(processWorkJButton)
                        .addGap(61, 61, 61)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(headingJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(patientDetailsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingJLabel)
                .addGap(18, 18, 18)
                .addComponent(refreshJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(processWorkJButton)
                            .addComponent(viewPateintsJButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(backJButton)))
                .addGap(15, 15, 15)
                .addComponent(patientDetailsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populatePatients();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void viewPateintsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPateintsJButtonActionPerformed
        int selectedRow = manageWorkRequestsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        WorkRequest wr = (WorkRequest) manageWorkRequestsJTable.getValueAt(selectedRow, 0);
        if (wr instanceof PharmacyWorkRequest) {
            PharmacyWorkRequest pwr = (PharmacyWorkRequest) wr;
            patientDetailsJPanel.setVisible(true);
            patientNameJTextField.setText(pwr.getPatient().getFirstName() + " " + pwr.getPatient().getLastName());
            mobilePhoneJjTextField.setText(String.valueOf(pwr.getPatient().getMobilePhone()));
            addressJTextField.setText(pwr.getPatient().getHomeAddress());
            cityJTextField.setText(pwr.getPatient().getCity());
            drugsJTextArea.setText(pwr.getDrugs().getDrugName());
        }

    }//GEN-LAST:event_viewPateintsJButtonActionPerformed

    private void processWorkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processWorkJButtonActionPerformed
        int selectedRow = manageWorkRequestsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        WorkRequest wr = (WorkRequest) manageWorkRequestsJTable.getValueAt(selectedRow, 0);
        if (wr instanceof PharmacyWorkRequest) {
            PharmacyWorkRequest pwr = (PharmacyWorkRequest) wr;
            pwr.setStatus("Your order has been dispatched");
            pwr.setPharmicistName(enterprise.getName());
            JOptionPane.showMessageDialog(null,"Succesfully, processed");
        }

    }//GEN-LAST:event_processWorkJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JTextArea drugsJTextArea;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable manageWorkRequestsJTable;
    private javax.swing.JTextField mobilePhoneJjTextField;
    private javax.swing.JPanel patientDetailsJPanel;
    private javax.swing.JTextField patientNameJTextField;
    private javax.swing.JButton processWorkJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton viewPateintsJButton;
    // End of variables declaration//GEN-END:variables
}
