/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PharmaciesRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmaciesEnterprise;
import Business.PharmaceuticalCompany.Drugs;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rimple
 */
public class ManageDrugsToPharmaciesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDrugsToPharmaciesJPanel
     */
    private JPanel userProcessContainer;
    private Ecosystem ecosystem;
    private Enterprise enterprise;
    private PharmaciesEnterprise pe;
    public ManageDrugsToPharmaciesJPanel(JPanel userProcessContainer, Ecosystem ecosystem, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.enterprise =enterprise;
        poptable();
    }
    
    private void poptable() {
        DefaultTableModel model = (DefaultTableModel) manageDrugsJTable.getModel();
        model.setRowCount(0);
         pe = (PharmaciesEnterprise)enterprise;
        for (Drugs drugs: pe.getDrugsList()) {
            
            Object[] row = new Object[3];
            row[0] = drugs;
            row[1] = drugs.getDrugName();
            row[2] = drugs.getManufacturingCo();
            
            model.addRow(row);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        addDrugsJButton = new javax.swing.JButton();
        viewDrugsJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageDrugsJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        deleteDrugsJButton = new javax.swing.JButton();

        headingJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headingJLabel.setText("Manage Drugs");

        addDrugsJButton.setText("Add Drugs");
        addDrugsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrugsJButtonActionPerformed(evt);
            }
        });

        viewDrugsJButton.setText("View Drugs");
        viewDrugsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDrugsJButtonActionPerformed(evt);
            }
        });

        manageDrugsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "Pharmaceutical Company Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageDrugsJTable);
        if (manageDrugsJTable.getColumnModel().getColumnCount() > 0) {
            manageDrugsJTable.getColumnModel().getColumn(2).setPreferredWidth(130);
        }

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        deleteDrugsJButton.setText("Delete Drugs");
        deleteDrugsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDrugsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(headingJLabel)
                        .addGap(107, 107, 107)
                        .addComponent(refreshJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addGap(46, 46, 46)
                                .addComponent(addDrugsJButton)
                                .addGap(36, 36, 36)
                                .addComponent(viewDrugsJButton)
                                .addGap(31, 31, 31)
                                .addComponent(deleteDrugsJButton)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headingJLabel)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(refreshJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDrugsJButton)
                    .addComponent(backJButton)
                    .addComponent(viewDrugsJButton)
                    .addComponent(deleteDrugsJButton))
                .addGap(113, 113, 113))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDrugsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrugsJButtonActionPerformed
        
        AddDrugsFromPCCompanyJPanel addDrugsFromPCCompanyJPanel = new AddDrugsFromPCCompanyJPanel(userProcessContainer, ecosystem, enterprise);
        userProcessContainer.add("addDrugsFromPCCompanyJPanel", addDrugsFromPCCompanyJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addDrugsJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        poptable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void viewDrugsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDrugsJButtonActionPerformed
        
        int selectedRow = manageDrugsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        Drugs drugs = (Drugs) manageDrugsJTable.getValueAt(selectedRow, 0);
        ViewDrugsToPharmaciesJPanel viewDrugsToPharmaciesJPanel = new ViewDrugsToPharmaciesJPanel(userProcessContainer, drugs);
        userProcessContainer.add("viewDrugsToPharmaciesJPanel", viewDrugsToPharmaciesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewDrugsJButtonActionPerformed

    private void deleteDrugsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDrugsJButtonActionPerformed
        
        int selectedRow = manageDrugsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        int selectedValue = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", "Warning", JOptionPane.YES_NO_OPTION);

        if (selectedValue == JOptionPane.YES_OPTION) {
            Drugs drugs = (Drugs) manageDrugsJTable.getValueAt(selectedRow, 0);
            if (enterprise instanceof PharmaciesEnterprise) {
             pe = (PharmaciesEnterprise) enterprise;
            }
            
            pe.deleteDrugs(drugs);
            poptable();
            
        }

        return;
    }//GEN-LAST:event_deleteDrugsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDrugsJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deleteDrugsJButton;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manageDrugsJTable;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton viewDrugsJButton;
    // End of variables declaration//GEN-END:variables
}
