/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AdminToAddDiseaseRole;

import Business.ManageDiseaseAdmin;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rimple
 */
public class AdminAddDiseaseWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminAddDiseaseWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private ManageDiseaseAdmin manageDiseaseAdmin;
    public AdminAddDiseaseWorkAreaJPanel(JPanel userProcessContainer,ManageDiseaseAdmin manageDiseaseAdmin) {
        initComponents();
        this.userProcessContainer =  userProcessContainer;
        this.manageDiseaseAdmin = manageDiseaseAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        manageDiseasesJButton = new javax.swing.JButton();

        headingJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headingJLabel.setText("My work area - Admin to add Disease");

        manageDiseasesJButton.setText("Manage Diseases");
        manageDiseasesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDiseasesJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(headingJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(manageDiseasesJButton)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingJLabel)
                .addGap(42, 42, 42)
                .addComponent(manageDiseasesJButton)
                .addContainerGap(323, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageDiseasesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDiseasesJButtonActionPerformed
        
        ManageDiseaseJPanel ManageDiseaseJPanel = new ManageDiseaseJPanel(userProcessContainer,manageDiseaseAdmin );
        userProcessContainer.add("ManageDiseaseJPanel", ManageDiseaseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDiseasesJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JButton manageDiseasesJButton;
    // End of variables declaration//GEN-END:variables
}
