/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminToAddDiseaseRole;

import Business.Disease;
import Business.ManageDiseaseAdmin;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rimple
 */
public class ManageDiseaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDiseaseJPanel
     */
    private JPanel userProcessContainer;
    private ManageDiseaseAdmin manageDiseaseAdmin;

    public ManageDiseaseJPanel(JPanel userProcessContainer, ManageDiseaseAdmin manageDiseaseAdmin) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.manageDiseaseAdmin = manageDiseaseAdmin;
        poptable();
    }

    private void poptable() {
        DefaultTableModel model = (DefaultTableModel) manageDiseaseJTable.getModel();
        model.setRowCount(0);
        for (Disease disease : manageDiseaseAdmin.getDiseaseList()) {
            Object[] row = new Object[4];
            row[0] = disease.getIcd9Code();
            row[1] = disease;
            row[2] = disease.getSymptoms();
            row[3] = disease.getDescription();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageDiseaseJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        icd9CodeJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        diseaseNameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        symptomsJTextArea = new javax.swing.JTextArea();
        addDiseaseJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        descriptionJTextField = new javax.swing.JTextField();

        headingJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headingJLabel.setText("Manage Diseases");

        manageDiseaseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ICD-9 Code", "Disease Name", "Symptoms", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageDiseaseJTable);

        jLabel1.setText("ICD-9 Code:");

        jLabel2.setText("Disease Name:");

        jLabel3.setText("Symptoms:");

        symptomsJTextArea.setColumns(20);
        symptomsJTextArea.setRows(5);
        jScrollPane2.setViewportView(symptomsJTextArea);

        addDiseaseJButton.setText("Add Disease");
        addDiseaseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDiseaseJButtonActionPerformed(evt);
            }
        });

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Description:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(headingJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53)
                                .addComponent(icd9CodeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(diseaseNameJTextField)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(descriptionJTextField, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(backJButton)
                        .addGap(150, 150, 150)
                        .addComponent(addDiseaseJButton)
                        .addGap(123, 123, 123)
                        .addComponent(refreshJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(icd9CodeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(diseaseNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(descriptionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDiseaseJButton)
                    .addComponent(refreshJButton)
                    .addComponent(backJButton))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        poptable();
        icd9CodeJTextField.setText("");
        diseaseNameJTextField.setText("");
        symptomsJTextArea.setText("");
        descriptionJTextField.setText("");
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void addDiseaseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDiseaseJButtonActionPerformed

        try {
            String icd9Code = icd9CodeJTextField.getText().trim();
            String diseaseName = diseaseNameJTextField.getText().trim();
            String symptoms = symptomsJTextArea.getText();
            String description = descriptionJTextField.getText().trim();

            if (("".equals(icd9Code)) || ("".equals(diseaseName)) || ("".equals(symptoms)) || ("".equals(description))) {
                JOptionPane.showMessageDialog(null, "Please do not keep any values empty.");
                return;
            }
            Disease d = new Disease();
            d.setIcd9Code(Float.parseFloat(icd9Code));
            d.setDiseaseName(diseaseName);
            d.setSymptoms(symptoms);
            d.setDescription(description);
            manageDiseaseAdmin.getDiseaseList().add(d);
            poptable();

            icd9CodeJTextField.setText("");
            diseaseNameJTextField.setText("");
            symptomsJTextArea.setText("");
            descriptionJTextField.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please use valid ICD9 - Code");
        }
    }//GEN-LAST:event_addDiseaseJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDiseaseJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField descriptionJTextField;
    private javax.swing.JTextField diseaseNameJTextField;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JTextField icd9CodeJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable manageDiseaseJTable;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTextArea symptomsJTextArea;
    // End of variables declaration//GEN-END:variables
}
