/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.Ecosystem;
import Business.Enterprise.ClinicEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PharmaciesEnterprise;
import Business.Network.NetworkCities;
import Business.Network.NetworkCountries;
import Business.Network.NetworkStates;
import Business.Person.Doctor;
import Business.Person.Patient;
import Business.WorkQueue.AssignEmergencyWorkRequest;
import Business.WorkQueue.EnquireEmergencyWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.PharmaceuticalCompanyEmployeeRole.ViewNotficationToNetworksJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rimple
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Ecosystem ecosystem;
    //private ArrayList<Enterprise> enterpriseList;
    private Doctor doctor;

    // private Enterprise enterprise;
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, Ecosystem ecosystem, Doctor doctor) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.doctor = doctor;
        //this.enterprise = enterprise;
        populateTable();

    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) manageTableJTable.getModel();
        model.setRowCount(0);
        for (WorkRequest wr : doctor.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof AssignEmergencyWorkRequest) {
                AssignEmergencyWorkRequest aewr = (AssignEmergencyWorkRequest)wr;

                Object[] row = new Object[4];
                row[0] = aewr;
                row[1] = aewr.getMRNo();
                row[2] = aewr.getPatientName();
                row[3] = aewr.getEnterprise();

                model.addRow(row);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        manageWorkRequetsJButton = new javax.swing.JButton();
        manageLabTestJButton = new javax.swing.JButton();
        viewDrugOrdersToPharmaciesJButton = new javax.swing.JButton();
        viewReferredDoctorRequestsJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageTableJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        sendEnquiryJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        manageEmergencyPatientsJButton = new javax.swing.JButton();
        viewNotifcationJButton = new javax.swing.JButton();

        headingJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headingJLabel.setText("My Work Area - Doctor Role");

        manageWorkRequetsJButton.setText("Manage Work Requests");
        manageWorkRequetsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageWorkRequetsJButtonActionPerformed(evt);
            }
        });

        manageLabTestJButton.setText("Manage Lab Test");
        manageLabTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageLabTestJButtonActionPerformed(evt);
            }
        });

        viewDrugOrdersToPharmaciesJButton.setText("View Drug orders to Pharmacies");
        viewDrugOrdersToPharmaciesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDrugOrdersToPharmaciesJButtonActionPerformed(evt);
            }
        });

        viewReferredDoctorRequestsJButton.setText("Vew Referred Doctor Requests");
        viewReferredDoctorRequestsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReferredDoctorRequestsJButtonActionPerformed(evt);
            }
        });

        manageTableJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Patient MR No.", "Patient Name", "Enterprise"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageTableJTable);
        if (manageTableJTable.getColumnModel().getColumnCount() > 0) {
            manageTableJTable.getColumnModel().getColumn(0).setPreferredWidth(200);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("View Emeregency Work Request:");

        sendEnquiryJButton.setText("Send Enquiry to Other Hospitals/Clinics");
        sendEnquiryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEnquiryJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Message:");

        manageEmergencyPatientsJButton.setText("Manage Emergency Patients");
        manageEmergencyPatientsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmergencyPatientsJButtonActionPerformed(evt);
            }
        });

        viewNotifcationJButton.setText("View Notification from Pharmaceutical Company");
        viewNotifcationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewNotifcationJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageEmergencyPatientsJButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(messageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(manageWorkRequetsJButton)
                        .addGap(378, 378, 378))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(manageLabTestJButton)
                        .addGap(391, 391, 391))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewDrugOrdersToPharmaciesJButton)
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sendEnquiryJButton)
                        .addGap(324, 324, 324))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(viewReferredDoctorRequestsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(headingJLabel)
                            .addGap(328, 328, 328)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewNotifcationJButton)
                        .addGap(306, 306, 306))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingJLabel)
                .addGap(39, 39, 39)
                .addComponent(manageWorkRequetsJButton)
                .addGap(12, 12, 12)
                .addComponent(manageLabTestJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewDrugOrdersToPharmaciesJButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewReferredDoctorRequestsJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewNotifcationJButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(messageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(sendEnquiryJButton)
                .addGap(46, 46, 46)
                .addComponent(manageEmergencyPatientsJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageWorkRequetsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageWorkRequetsJButtonActionPerformed

        ManageDoctorWorkRequestJPanel manageDoctorWorkRequestJPanel = new ManageDoctorWorkRequestJPanel(userProcessContainer, doctor, ecosystem);
        userProcessContainer.add("manageDoctorWorkRequestJPanel", manageDoctorWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageWorkRequetsJButtonActionPerformed

    private void manageLabTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageLabTestJButtonActionPerformed
        // TODO add your handling code here:
        ManageLabTestJPanel manageLabTestJPanel = new ManageLabTestJPanel(userProcessContainer, doctor, ecosystem);
        userProcessContainer.add("manageLabTestJPanel", manageLabTestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageLabTestJButtonActionPerformed

    private void viewDrugOrdersToPharmaciesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDrugOrdersToPharmaciesJButtonActionPerformed

        ViewOrdersToPharmaciesForDoctorsJPanel viewOrdersToPharmaciesForDoctorsJPanel = new ViewOrdersToPharmaciesForDoctorsJPanel(userProcessContainer, doctor);
        userProcessContainer.add("viewOrdersToPharmaciesForDoctorsJPanel", viewOrdersToPharmaciesForDoctorsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_viewDrugOrdersToPharmaciesJButtonActionPerformed

    private void viewReferredDoctorRequestsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReferredDoctorRequestsJButtonActionPerformed

        ViewReferredDoctorRequestsJPanel viewReferredDoctorRequestsJPanel = new ViewReferredDoctorRequestsJPanel(userProcessContainer, doctor);
        userProcessContainer.add("viewReferredDoctorRequestsJPanel", viewReferredDoctorRequestsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_viewReferredDoctorRequestsJButtonActionPerformed

    private void sendEnquiryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEnquiryJButtonActionPerformed

        int selectedRow = manageTableJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        int MRNo = (int) manageTableJTable.getValueAt(selectedRow, 1);
        Enterprise SenderEnterprise = (Enterprise) manageTableJTable.getValueAt(selectedRow, 3);
        WorkRequest wr = (WorkRequest)manageTableJTable.getValueAt(selectedRow,0);
        String message = messageJTextField.getText();
        if ("".equals(message)) {
            JOptionPane.showMessageDialog(null, "Please write a message");
            return;
        }
        EnquireEmergencyWorkRequest eewr = new EnquireEmergencyWorkRequest();
        eewr.setDoctor(doctor);
        eewr.setMrNo(MRNo);
        eewr.setEnterprise(SenderEnterprise);
        eewr.setMessage(message);
        doctor.getWorkQueue().getWorkRequestList().add(eewr);
        for (NetworkCountries networkCountries : ecosystem.getNetworkListsCountries()) {
            for (NetworkStates networkStates : networkCountries.getNetworkListStates()) {
                for (NetworkCities networkCities : networkStates.getNetworkListCities()) {
                    for (Enterprise enterprise : networkCities.getEnterpriseDirectory().getEnterpriseList()) {
                        if (enterprise instanceof HospitalEnterprise || enterprise instanceof ClinicEnterprise) {
                            enterprise.getWorkQueue().getWorkRequestList().add(eewr);
                            
                        }
                    }
                }
            }
        }
        JOptionPane.showMessageDialog(null,"Enquiry sent.");
        messageJTextField.setText("");
        doctor.getWorkQueue().getWorkRequestList().remove(wr);
        populateTable();
    }//GEN-LAST:event_sendEnquiryJButtonActionPerformed

    private void manageEmergencyPatientsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmergencyPatientsJButtonActionPerformed

        ManageEmergencyPatientsJPanel manageEmergencyPatientsJPanel = new ManageEmergencyPatientsJPanel(userProcessContainer, doctor);
        userProcessContainer.add("manageEmergencyPatientsJPanel", manageEmergencyPatientsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmergencyPatientsJButtonActionPerformed

    private void viewNotifcationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewNotifcationJButtonActionPerformed
        
        ViewNotficationToNetworksJPanel viewNotficationDoctors = new ViewNotficationToNetworksJPanel(userProcessContainer,doctor.getWorkQueue());
        userProcessContainer.add("viewNotficationDoctors", viewNotficationDoctors);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewNotifcationJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageEmergencyPatientsJButton;
    private javax.swing.JButton manageLabTestJButton;
    private javax.swing.JTable manageTableJTable;
    private javax.swing.JButton manageWorkRequetsJButton;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JButton sendEnquiryJButton;
    private javax.swing.JButton viewDrugOrdersToPharmaciesJButton;
    private javax.swing.JButton viewNotifcationJButton;
    private javax.swing.JButton viewReferredDoctorRequestsJButton;
    // End of variables declaration//GEN-END:variables
}
