/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DoctorRole;

import Business.Ecosystem;
import Business.Enterprise.PharmaceuticalCompaniesEnterprise;
import Business.Person.Doctor;
import Business.PharmaceuticalCompany.Drugs;
import Business.WorkQueue.FeedbackToPCWorkRequest;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.PharmaceuticalCompanyEmployeeRole.ViewGuidelinesPag1JPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rimple
 */
public class ViewOrdersToPharmaciesForDoctorsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDrugOrdersToPharmaciesForDoctorsJPanel
     */
    private JPanel userProcessContainer;
    private Doctor doctor;
    public ViewOrdersToPharmaciesForDoctorsJPanel(JPanel userProcessContainer,Doctor doctor ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.doctor = doctor;
        populateDrugs();
        feedbackJPanel.setVisible(false);
    }

    private void populateDrugs() {
        DefaultTableModel model = (DefaultTableModel) manageTableJTable.getModel();
        model.setRowCount(0);
        for (WorkRequest wr : doctor.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof PharmacyWorkRequest) {
                PharmacyWorkRequest pwr = (PharmacyWorkRequest) wr;
                Object[] row = new Object[7];
                row[0] = pwr;
                row[1] = pwr.getPatient().getFirstName() + " " + pwr.getPatient().getLastName();
                row[2] = pwr.getEnterprise();
                row[3] = pwr.getDrugs().getDrugID();
                row[4] = pwr.getDrugs().getDrugName();
                row[5] = pwr.getPharmicistName();
                row[6] = pwr.getStatus();
                model.addRow(row);

            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        manageTableJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        feedbackJButton = new javax.swing.JButton();
        feedbackJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        feedbackJTextArea = new javax.swing.JTextArea();
        sendJButton = new javax.swing.JButton();
        viewGuidelinesJButton = new javax.swing.JButton();

        headingJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headingJLabel.setText("View Drug Orders");

        manageTableJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Patient Name", "Enterprise", "Drug ID", "Drug Name", "Pharmacy Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(manageTableJTable);

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        feedbackJButton.setText("Share feedback");
        feedbackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Feedback");

        feedbackJTextArea.setColumns(20);
        feedbackJTextArea.setRows(5);
        jScrollPane4.setViewportView(feedbackJTextArea);

        sendJButton.setText("Send");
        sendJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout feedbackJPanelLayout = new javax.swing.GroupLayout(feedbackJPanel);
        feedbackJPanel.setLayout(feedbackJPanelLayout);
        feedbackJPanelLayout.setHorizontalGroup(
            feedbackJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(feedbackJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(feedbackJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackJPanelLayout.createSequentialGroup()
                        .addComponent(sendJButton)
                        .addGap(103, 103, 103))))
        );
        feedbackJPanelLayout.setVerticalGroup(
            feedbackJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(feedbackJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(feedbackJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackJPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(sendJButton)
                .addGap(28, 28, 28))
        );

        viewGuidelinesJButton.setText("View Drug Guidelines");
        viewGuidelinesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewGuidelinesJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(headingJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(feedbackJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(backJButton)
                        .addGap(129, 129, 129)
                        .addComponent(feedbackJButton)
                        .addGap(95, 95, 95)
                        .addComponent(viewGuidelinesJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingJLabel)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feedbackJButton)
                    .addComponent(viewGuidelinesJButton)
                    .addComponent(backJButton))
                .addGap(8, 8, 8)
                .addComponent(feedbackJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void feedbackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackJButtonActionPerformed
        int selectedRow = manageTableJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        feedbackJPanel.setVisible(true);

    }//GEN-LAST:event_feedbackJButtonActionPerformed

    private void sendJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendJButtonActionPerformed
        int selectedRow = manageTableJTable.getSelectedRow();
        String feedback = feedbackJTextArea.getText();
        if("".equals(feedback)){
            JOptionPane.showMessageDialog(null, "Please write the feedback");
            return;
        }
        PharmacyWorkRequest pwr = (PharmacyWorkRequest) manageTableJTable.getValueAt(selectedRow, 0);
        Drugs d = (Drugs)pwr.getDrugs();
        PharmaceuticalCompaniesEnterprise pce = (PharmaceuticalCompaniesEnterprise)d.getManufacturingCo();

        FeedbackToPCWorkRequest request = new FeedbackToPCWorkRequest();
        request.setMessage(feedback);
        request.setSender(doctor);
        request.setDrug(d);
        pce.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null,"Your feedback has been sent");
        feedbackJPanel.setVisible(false);
    }//GEN-LAST:event_sendJButtonActionPerformed

    private void viewGuidelinesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGuidelinesJButtonActionPerformed
        
        int selectedRow = manageTableJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        //Drugs d = (Drugs)manageTableJTable.getValueAt(selectedRow,3);
        PharmacyWorkRequest pwr = (PharmacyWorkRequest) manageTableJTable.getValueAt(selectedRow, 0);
        Drugs d = (Drugs)pwr.getDrugs();
        ViewGuidelinesPag1JPanel viewGuidelinesPag1JPanel = new ViewGuidelinesPag1JPanel(userProcessContainer, d);
        userProcessContainer.add("viewGuidelinesPag1JPanel", viewGuidelinesPag1JPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewGuidelinesJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton feedbackJButton;
    private javax.swing.JPanel feedbackJPanel;
    private javax.swing.JTextArea feedbackJTextArea;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable manageTableJTable;
    private javax.swing.JButton sendJButton;
    private javax.swing.JButton viewGuidelinesJButton;
    // End of variables declaration//GEN-END:variables
}
