/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmaceuticalCompanyEmployeeRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmaceuticalCompaniesEnterprise;
import Business.PharmaceuticalCompany.Drugs;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rimple
 */
public class AddDrugsToPCEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDrugsToPCEmployeeJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private PharmaceuticalCompaniesEnterprise pce;

    public AddDrugsToPCEmployeeJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        drugNamejTextField = new javax.swing.JTextField();
        specificationsJTextField = new javax.swing.JTextField();
        priceJTextField = new javax.swing.JTextField();
        strengthJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        specificationJComboBox = new javax.swing.JComboBox();
        addMedicationGuidelinesJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        headingJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headingJLabel.setText("Add Drugs");

        jLabel1.setText("Drug Name:");

        jLabel2.setText("Strength:");

        jLabel3.setText("Specifications:");

        jLabel4.setText("Price:");

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        specificationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mg", "ml" }));

        addMedicationGuidelinesJButton.setText("Add Medication Guidelines");
        addMedicationGuidelinesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedicationGuidelinesJButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(priceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(specificationsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(drugNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(strengthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(specificationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(headingJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)
                        .addGap(77, 77, 77)
                        .addComponent(addMedicationGuidelinesJButton)))
                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingJLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(drugNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(strengthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(specificationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(specificationsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(priceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addMedicationGuidelinesJButton)
                            .addComponent(backJButton))))
                .addGap(270, 270, 270))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addMedicationGuidelinesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicationGuidelinesJButtonActionPerformed
        // TODO add your handling code here:
        try {
            String drugName = drugNamejTextField.getText().trim();
            String specifications = specificationsJTextField.getText().trim();
            String strength = strengthJTextField.getText().trim();
            String price = priceJTextField.getText().trim();

            if (("".equals(drugName)) || ("".equals(specifications)) || ("".equals(strength)) || ("".equals(price))) {
                JOptionPane.showMessageDialog(null, "Please do not keep any values empty.");
                return;
            }
            Drugs d = new Drugs();
            d.setDrugName(drugName);
            if (specificationJComboBox.getSelectedIndex() == 0) {
                d.setSpecifiations(specifications + " mg");
            }
            if (specificationJComboBox.getSelectedIndex() == 1) {
                d.setSpecifiations(specifications + " ml");
            }
            d.setStrength(Float.parseFloat(strength));
            d.setPrice(Float.parseFloat(price));
            if (enterprise instanceof PharmaceuticalCompaniesEnterprise) {
                pce = (PharmaceuticalCompaniesEnterprise) enterprise;
            }
            d.setManufacturingCo(pce);

            AddMedicationGuidelinesPage1JPanel addMedicationGuidelinesPage1JPanel = new AddMedicationGuidelinesPage1JPanel(userProcessContainer, d, enterprise);
            userProcessContainer.add("addMedicationGuidelinesPage1JPanel", addMedicationGuidelinesPage1JPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please use number for price and strength");
        }
    }//GEN-LAST:event_addMedicationGuidelinesJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMedicationGuidelinesJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField drugNamejTextField;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField priceJTextField;
    private javax.swing.JComboBox specificationJComboBox;
    private javax.swing.JTextField specificationsJTextField;
    private javax.swing.JTextField strengthJTextField;
    // End of variables declaration//GEN-END:variables
}
