/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmaceuticalCompanyEmployeeRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmaceuticalCompaniesEnterprise;
import Business.Enterprise.PharmaciesEnterprise;
import Business.PharmaceuticalCompany.Drugs;
import Business.WorkQueue.CallBackDrugWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rimple
 */
public class CallBackDrugsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CallBackDrugsJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;

    public CallBackDrugsJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateTable();
        reasonJPanel.setVisible(false);
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) manageDrugsJTable.getModel();
        model.setRowCount(0);
        if (enterprise instanceof PharmaceuticalCompaniesEnterprise) {
            PharmaceuticalCompaniesEnterprise pce = (PharmaceuticalCompaniesEnterprise) enterprise;
            for (Drugs d : pce.getDrugsList()) {
                if(d.getIsApproved() == null ? Drugs.Approved_Status == null : d.getIsApproved().equals(Drugs.Approved_Status)){
                Object[] row = new Object[3];
                row[0] = d;
                row[1] = d.getDrugName();
                row[2] = d.getIsApproved();

                model.addRow(row);
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageDrugsJTable = new javax.swing.JTable();
        sendMessageJButton = new javax.swing.JButton();
        reasonJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        reasonJTextArea = new javax.swing.JTextArea();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        headingJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headingJLabel.setText("Call Back Drug Request");

        manageDrugsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageDrugsJTable);

        sendMessageJButton.setText("Send New Message");
        sendMessageJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Reason to Call Back:");

        reasonJTextArea.setColumns(20);
        reasonJTextArea.setRows(5);
        jScrollPane2.setViewportView(reasonJTextArea);

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reasonJPanelLayout = new javax.swing.GroupLayout(reasonJPanel);
        reasonJPanel.setLayout(reasonJPanelLayout);
        reasonJPanelLayout.setHorizontalGroup(
            reasonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reasonJPanelLayout.createSequentialGroup()
                .addGroup(reasonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reasonJPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reasonJPanelLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(submitJButton)))
                .addContainerGap())
        );
        reasonJPanelLayout.setVerticalGroup(
            reasonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reasonJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reasonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitJButton)
                .addContainerGap())
        );

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(headingJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(backJButton)
                        .addGap(162, 162, 162)
                        .addComponent(sendMessageJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(reasonJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingJLabel)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendMessageJButton)
                    .addComponent(backJButton))
                .addGap(32, 32, 32)
                .addComponent(reasonJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendMessageJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageJButtonActionPerformed
        int selectedRow = manageDrugsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        reasonJPanel.setVisible(true);
    }//GEN-LAST:event_sendMessageJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        String reason = reasonJTextArea.getText();
        int selectedRow = manageDrugsJTable.getSelectedRow();
        Drugs drugs = (Drugs) manageDrugsJTable.getValueAt(selectedRow, 0);

        if ("".equals(reason)) {
            JOptionPane.showMessageDialog(null, "Please write a reason to call back");
            return;
        }

        CallBackDrugWorkRequest request = new CallBackDrugWorkRequest();
        request.setMessage(reason);
        request.setDrug(drugs);
        request.setEnterprise(enterprise);
        request.getDrug().setIsApproved("Call Back");
        enterprise.getWorkQueue().getWorkRequestList().add(request);
        if (enterprise instanceof PharmaceuticalCompaniesEnterprise) {
            PharmaceuticalCompaniesEnterprise pce = (PharmaceuticalCompaniesEnterprise) enterprise;
            for (PharmaciesEnterprise pe : pce.getPharmaciesEnterpriseList()) {
                pe.getWorkQueue().getWorkRequestList().add(request);
            }
        }

        reasonJPanel.setVisible(false);
        reasonJTextArea.setText("");
    }//GEN-LAST:event_submitJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable manageDrugsJTable;
    private javax.swing.JPanel reasonJPanel;
    private javax.swing.JTextArea reasonJTextArea;
    private javax.swing.JButton sendMessageJButton;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
